<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBxYOkRS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBxYOkRS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBxYOkRS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBxYOkRS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBxYOkRS\App_KernelDevDebugContainer([
    'container.build_hash' => 'BxYOkRS',
    'container.build_id' => 'ac9e3d17',
    'container.build_time' => 1702376532,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBxYOkRS');
