<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFOs7Rl1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFOs7Rl1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFOs7Rl1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFOs7Rl1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFOs7Rl1\App_KernelDevDebugContainer([
    'container.build_hash' => 'FOs7Rl1',
    'container.build_id' => '849e9b4a',
    'container.build_time' => 1702889797,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFOs7Rl1');
